// Auto-generated search index - DO NOT EDIT MANUALLY
// Generated by: node scripts/generate-search-index.mjs

export interface SearchItem {
  title: string
  slug: string
  section: "docs" | "vignette"
  lang: "r" | "python"
  locale: string
  content: string
  url: string
}

export const searchData: SearchItem[] = [
  {
    "title": "Annotation Boost Plus (Optional)",
    "slug": "annotation-boost-extra",
    "section": "docs",
    "lang": "python",
    "locale": "en",
    "content": "This can be used to study a given problem related to a cluster, such as infer the state of a cluster. Here we use the cd8-positive, alpha-beta t cell as an example. Note that the performance of this a",
    "url": "/en/docs/python/annotation-boost-extra"
  },
  {
    "title": "Annotation Boost (Optional)",
    "slug": "annotation-boost",
    "section": "docs",
    "lang": "python",
    "locale": "en",
    "content": "Annotation Boost is an advanced validation tool that enhances annotation confidence through multiple iterations of analysis. It's particularly useful for: - Validating low-confidence annotations - Get",
    "url": "/en/docs/python/annotation-boost"
  },
  {
    "title": "Batch Processing",
    "slug": "batch-processing",
    "section": "docs",
    "lang": "python",
    "locale": "en",
    "content": "CASSIA supports batch processing to analyze multiple clusters simultaneously. This guide explains how to run batch analysis efficiently. Preparing Marker Data For Python, marker data is typically load",
    "url": "/en/docs/python/batch-processing"
  },
  {
    "title": "Symphony Compare (Optional)",
    "slug": "compare-cell-types",
    "section": "docs",
    "lang": "python",
    "locale": "en",
    "content": "The symphonyCompare agent acts as a virtual panel of experts to resolve ambiguous cell type annotations. It orchestrates multiple AI models (a \"Symphony\" of agents) to compare potential cell types, de",
    "url": "/en/docs/python/compare-cell-types"
  },
  {
    "title": "Fast Mode",
    "slug": "fast-mode",
    "section": "docs",
    "lang": "python",
    "locale": "en",
    "content": "CASSIA's Fast Mode offers a streamlined, one-line solution for running the complete analysis pipeline. This mode combines annotation, scoring, and annotation boost for correcting low quality annotatio",
    "url": "/en/docs/python/fast-mode"
  },
  {
    "title": "Introduction to Optional Agents",
    "slug": "introduction-to-optional-agents",
    "section": "docs",
    "lang": "python",
    "locale": "en",
    "content": "Thank you for reading this far! The basic CASSIA workflow is sufficient for most situations. However, to handle some special cases, we now introduce several advanced agents. 🤔 Uncertainty Quantificat",
    "url": "/en/docs/python/introduction-to-optional-agents"
  },
  {
    "title": "Introduction",
    "slug": "introduction",
    "section": "docs",
    "lang": "python",
    "locale": "en",
    "content": "Welcome to the CASSIA Python tutorial! This guide will walk you through using the CASSIA package in Python for cell type annotation. What is CASSIA? CASSIA (Collaborative Agent System for Single-cell ",
    "url": "/en/docs/python/introduction"
  },
  {
    "title": "Quality Scoring",
    "slug": "quality-scoring-and-report-generation",
    "section": "docs",
    "lang": "python",
    "locale": "en",
    "content": "Quality scoring helps evaluate the reliability of cell type annotations. CASSIA provides automated scoring functionality through the runCASSIAscorebatch function, which analyzes the reasoning and evid",
    "url": "/en/docs/python/quality-scoring-and-report-generation"
  },
  {
    "title": "RAG (Optional)",
    "slug": "ragagent",
    "section": "docs",
    "lang": "python",
    "locale": "en",
    "content": "This is particularly useful if you have a very specific and detialed annottaion to work with. It can significantly imrpove the granularity and accuracy of the annotation. It automatically extract mark",
    "url": "/en/docs/python/ragagent"
  },
  {
    "title": "Setting Up CASSIA",
    "slug": "setting-up-cassia",
    "section": "docs",
    "lang": "python",
    "locale": "en",
    "content": "First, install the CASSIA package using pip: Import CASSIA Setting API Keys To use LLMs like OpenAI's GPT-4, Anthropic's Claude, or models via OpenRouter, you will first need to get your API keys from",
    "url": "/en/docs/python/setting-up-cassia"
  },
  {
    "title": "Subclustering Analysis (Optional)",
    "slug": "subclustering-analysis",
    "section": "docs",
    "lang": "python",
    "locale": "en",
    "content": "Subclustering analysis is a powerful technique for studying specific cell populations in greater detail. This tutorial walks you through the process of analyzing subclustered populations, such as T ce",
    "url": "/en/docs/python/subclustering-analysis"
  },
  {
    "title": "Troubleshooting",
    "slug": "troubleshooting",
    "section": "docs",
    "lang": "python",
    "locale": "en",
    "content": "Here we list some common errors users may encounter. If you have any other questions, feel free to leave a comment in the last section! Authentication Errors (Error 401) Common Causes API key not prop",
    "url": "/en/docs/python/troubleshooting"
  },
  {
    "title": "Uncertainty Quantification (Optional)",
    "slug": "uncertainty-quantification",
    "section": "docs",
    "lang": "python",
    "locale": "en",
    "content": "Uncertainty quantification in CASSIA helps assess annotation reliability through multiple analysis iterations and similarity scoring. This process is crucial for: - Identifying robust cell type assign",
    "url": "/en/docs/python/uncertainty-quantification"
  },
  {
    "title": "Annotation Boost Plus (Optional)",
    "slug": "annotation-boost-extra",
    "section": "docs",
    "lang": "r",
    "locale": "en",
    "content": "This agent is an extended version of the annotation boost agent. It performs additional analysis on a specific cluster using a custom analysis task. This function extends the basic annotation capabili",
    "url": "/en/docs/r/annotation-boost-extra"
  },
  {
    "title": "Annotation Boost (Optional)",
    "slug": "annotation-boost",
    "section": "docs",
    "lang": "r",
    "locale": "en",
    "content": "Annotation Boost is an advanced validation tool that enhances annotation confidence through multiple iterations of analysis. It's particularly useful for: - Validating low-confidence annotations - Get",
    "url": "/en/docs/r/annotation-boost"
  },
  {
    "title": "Batch Processing",
    "slug": "batch-processing",
    "section": "docs",
    "lang": "r",
    "locale": "en",
    "content": "CASSIA supports batch processing to analyze multiple clusters simultaneously. This guide explains how to prepare your data and run batch analysis efficiently. Model Recommendations For detailed inform",
    "url": "/en/docs/r/batch-processing"
  },
  {
    "title": "Symphony Compare (Advanced)",
    "slug": "compare-cell-types",
    "section": "docs",
    "lang": "r",
    "locale": "en",
    "content": "symphonyCompare is an advanced module that orchestrates multiple AI models to compare cell types with automatic consensus building. It conducts a comprehensive cell type comparison using multiple AI m",
    "url": "/en/docs/r/compare-cell-types"
  },
  {
    "title": "Fast Mode",
    "slug": "fast-mode",
    "section": "docs",
    "lang": "r",
    "locale": "en",
    "content": "CASSIA's Fast Mode offers a streamlined, one-line solution for running the complete analysis pipeline. This mode combines annotation, scoring, and annotation boost for correcting low quality annotatio",
    "url": "/en/docs/r/fast-mode"
  },
  {
    "title": "Introduction to Optional Agents",
    "slug": "introduction-to-optional-agents",
    "section": "docs",
    "lang": "r",
    "locale": "en",
    "content": "Thank you for reading this far! The basic CASSIA workflow is sufficient for most situations. However, to handle some special cases, we now introduce several advanced agents. 🤔 Uncertainty Quantificat",
    "url": "/en/docs/r/introduction-to-optional-agents"
  },
  {
    "title": "Introduction",
    "slug": "introduction",
    "section": "docs",
    "lang": "r",
    "locale": "en",
    "content": "Welcome to the CASSIA R tutorial! This guide will walk you through using the CASSIA package in R for cell type annotation. What is CASSIA? CASSIA (Collaborative Agent System for Single-cell Interpreta",
    "url": "/en/docs/r/introduction"
  },
  {
    "title": "Quality Scoring",
    "slug": "quality-scoring-and-report-generation",
    "section": "docs",
    "lang": "r",
    "locale": "en",
    "content": "Quality scoring helps evaluate the reliability of cell type annotations. CASSIA provides automated scoring functionality through the runCASSIAscorebatch function, which analyzes the reasoning and evid",
    "url": "/en/docs/r/quality-scoring-and-report-generation"
  },
  {
    "title": "RAG (Optional)",
    "slug": "ragagent",
    "section": "docs",
    "lang": "r",
    "locale": "en",
    "content": "While the RAG (Retrieval-Augmented Generation) agent significantly enhances annotation accuracy in complex or literature-scarce settings, it is currently implemented only in the Python version of the ",
    "url": "/en/docs/r/ragagent"
  },
  {
    "title": "Setting Up CASSIA",
    "slug": "setting-up-cassia",
    "section": "docs",
    "lang": "r",
    "locale": "en",
    "content": "First, ensure you have the reticulate package and the devtools package installed. Next, you can install the CASSIA package from github: Setting Up the Python Environment CASSIA relies on Python for so",
    "url": "/en/docs/r/setting-up-cassia"
  },
  {
    "title": "Single Cluster Analysis",
    "slug": "single-cluster-analysis",
    "section": "docs",
    "lang": "r",
    "locale": "en",
    "content": "The runCASSIA function analyzes a single cluster of marker genes to identify the cell type. Note that CASSIA is designed to handle multiple clusters at once, this function is specifically designed for",
    "url": "/en/docs/r/single-cluster-analysis"
  },
  {
    "title": "Subclustering Analysis (Optional)",
    "slug": "subclustering-analysis",
    "section": "docs",
    "lang": "r",
    "locale": "en",
    "content": "Subclustering analysis is a powerful technique for studying specific cell populations in greater detail. This tutorial walks you through the process of analyzing subclustered populations, such as T ce",
    "url": "/en/docs/r/subclustering-analysis"
  },
  {
    "title": "Troubleshooting",
    "slug": "troubleshooting",
    "section": "docs",
    "lang": "r",
    "locale": "en",
    "content": "Here we list some common errors users may encounter. If you have any other questions, feel free to leave a comment in the last section! Authentication Errors (Error 401) Common Causes API key not prop",
    "url": "/en/docs/r/troubleshooting"
  },
  {
    "title": "Uncertainty Quantification (Optional)",
    "slug": "uncertainty-quantification",
    "section": "docs",
    "lang": "r",
    "locale": "en",
    "content": "Uncertainty quantification in CASSIA helps assess annotation reliability through multiple analysis iterations and similarity scoring. This process is crucial for: - Identifying robust cell type assign",
    "url": "/en/docs/r/uncertainty-quantification"
  },
  {
    "title": "Basic Annotation",
    "slug": "basic-annotation",
    "section": "vignette",
    "lang": "python",
    "locale": "en",
    "content": "This Python tutorial demonstrates a complete workflow using CASSIA for cell type annotation of single-cell RNA sequencing data. We'll analyze an intestinal cell dataset containing six distinct populat",
    "url": "/en/vignette/python/basic-annotation"
  },
  {
    "title": "Clustering and Annotation with Scanpy",
    "slug": "clustering-and-annotation",
    "section": "vignette",
    "lang": "python",
    "locale": "en",
    "content": "This vignette demonstrates how to perform clustering on a pre-processed AnnData object using Scanpy and then annotate the resulting clusters using CASSIA. We'll assume quality control steps have alrea",
    "url": "/en/vignette/python/clustering-and-annotation"
  },
  {
    "title": "Extended Analysis",
    "slug": "extended-analysis",
    "section": "vignette",
    "lang": "python",
    "locale": "en",
    "content": "This tutorial covers advanced features of CASSIA, including uncertainty quantification, annotation boost, and specialized agents. Optional Step: Uncertainty Quantification This could be useful to stud",
    "url": "/en/vignette/python/extended-analysis"
  },
  {
    "title": "Introduction to Vignettes",
    "slug": "introduction",
    "section": "vignette",
    "lang": "python",
    "locale": "en",
    "content": "Welcome to the CASSIA Python vignettes section. Here we provide step-by-step tutorials with real data to help you understand the full workflow and capabilities of CASSIA. Available Vignettes 1. Basic ",
    "url": "/en/vignette/python/introduction"
  },
  {
    "title": "Getting Started with CASSIA: Basic Analysis",
    "slug": "basic-analysis",
    "section": "vignette",
    "lang": "r",
    "locale": "en",
    "content": "This vignette covers the fundamental steps to get started with CASSIA for single-cell RNA sequencing analysis. We'll focus on the essential workflow for basic cell type annotation. 1. Installation and",
    "url": "/en/vignette/r/basic-analysis"
  },
  {
    "title": "Basic Annotation with Marker Files",
    "slug": "basic-annotation",
    "section": "vignette",
    "lang": "r",
    "locale": "en",
    "content": "This vignette covers the fundamental steps to use CASSIA for cell type annotation when you already have marker gene lists prepared. This is ideal when you've already performed clustering analysis and ",
    "url": "/en/vignette/r/basic-annotation"
  },
  {
    "title": "Clustering and Annotation with Seurat",
    "slug": "clustering-and-annotation",
    "section": "vignette",
    "lang": "r",
    "locale": "en",
    "content": "This vignette demonstrates how to perform clustering on a pre-processed Seurat object and then annotate the resulting clusters using CASSIA. We'll assume quality control steps have already been comple",
    "url": "/en/vignette/r/clustering-and-annotation"
  },
  {
    "title": "Extended Analysis with Optional Agents",
    "slug": "extended-analysis",
    "section": "vignette",
    "lang": "r",
    "locale": "en",
    "content": "This vignette demonstrates how to use CASSIA's optional agents for deeper analysis and validation, starting from a provided marker file. These agents help you: - Assess annotation uncertainty - Boost ",
    "url": "/en/vignette/r/extended-analysis"
  },
  {
    "title": "Introduction to Vignettes",
    "slug": "introduction",
    "section": "vignette",
    "lang": "r",
    "locale": "en",
    "content": "Welcome to the CASSIA vignettes section. Here we provide step-by-step tutorials with real data to help you understand the full workflow and capabilities of CASSIA. Available Vignettes Our vignettes ar",
    "url": "/en/vignette/r/introduction"
  },
  {
    "title": "注释增强 Plus（可选）",
    "slug": "annotation-boost-extra",
    "section": "docs",
    "lang": "python",
    "locale": "zh",
    "content": "这可以用来研究与聚类相关的特定问题，例如推断聚类的状态。这里我们以 cd8 阳性 alpha-beta T 细胞为例。请注意，该智能体的性能尚未经过基准测试，因此请谨慎对待结果。 用法",
    "url": "/zh/docs/python/annotation-boost-extra"
  },
  {
    "title": "注释增强（可选）",
    "slug": "annotation-boost",
    "section": "docs",
    "lang": "python",
    "locale": "zh",
    "content": "注释增强是一种高级验证工具，通过多次分析迭代增强注释置信度。它特别适用于： - 验证低置信度注释 - 深入了解特定细胞聚类 - 解决模棱两可的细胞类型分配 - 生成全面的验证报告 所需组件 1. 输入数据： - 来自 CASSIA 批量分析的完整结果 CSV - 原始标记基因文件（注意：标记文件不应被过滤！） - 聚类背景信息 - 特定聚类标识符 2. 模型配置： - 推荐：通过 OpenRout",
    "url": "/zh/docs/python/annotation-boost"
  },
  {
    "title": "批量处理",
    "slug": "batch-processing",
    "section": "docs",
    "lang": "python",
    "locale": "zh",
    "content": "CASSIA 支持批量处理以同时分析多个聚类。本指南说明如何高效地运行批量分析。 准备标记数据 对于 Python，标记数据通常从 CSV 或处理过的数据帧加载。 运行批量分析 参数详情 - marker: 标记数据（DataFrame 或文件路径）。数据应包含聚类 ID 和基因名称。 - outputname: 输出文件的基本名称。 - model: 要使用的模型（例如，\"anthropic/c",
    "url": "/zh/docs/python/batch-processing"
  },
  {
    "title": "Symphony Compare (Optional)",
    "slug": "compare-cell-types",
    "section": "docs",
    "lang": "python",
    "locale": "zh",
    "content": "symphonyCompare 智能体充当虚拟专家小组来解决模棱两可的细胞类型注释。它协调多个 AI 模型（智能体“交响乐团”）来比较潜在的细胞类型，在讨论轮次中辩论它们的发现，并根据标记基因证据达成共识。 用法 此智能体在运行默认 CASSIA 流程后特别有用，如果您不确定特定聚类的身份。例如，区分浆细胞的不同亚型。 参数详情 - tissue: 正在分析的组织类型（例如，“大肠”）。 - ce",
    "url": "/zh/docs/python/compare-cell-types"
  },
  {
    "title": "快速模式",
    "slug": "fast-mode",
    "section": "docs",
    "lang": "python",
    "locale": "zh",
    "content": "CASSIA 的快速模式提供了一个精简的、单行解决方案来运行完整的分析流程。此模式在单个函数调用中结合了注释、评分和用于纠正低质量注释的注释增强，使用优化的默认参数。 基本用法 参数详情 - outputfilename: 输出文件夹和文件的基本名称。 - tissue: 样本的组织类型（例如，“脑”）。 - species: 样本的物种（例如，“人类”）。 - markerpath: 标记基因数",
    "url": "/zh/docs/python/fast-mode"
  },
  {
    "title": "可选智能体介绍",
    "slug": "introduction-to-optional-agents",
    "section": "docs",
    "lang": "python",
    "locale": "zh",
    "content": "感谢您读到这里！基本的 CASSIA 工作流程对于大多数情况来说已经足够了。但是，为了处理一些特殊情况，我们现在介绍几个高级智能体。 🤔 不确定性量化智能体 (UQ Agent) 大语言模型 (LLM) 虽然功能强大，但有时会产生可变的输出。不确定性量化 (UQ) 智能体通过采用基于共识的策略来缓解这一问题。例如，如果一个模型在一次尝试中的正确率为 80%，那么独立查询五次并通过多数投票汇总结果",
    "url": "/zh/docs/python/introduction-to-optional-agents"
  },
  {
    "title": "简介",
    "slug": "introduction",
    "section": "docs",
    "lang": "python",
    "locale": "zh",
    "content": "欢迎来到 CASSIA Python 教程！本指南将带您了解如何在 Python 中使用 CASSIA 包进行细胞类型注释。 什么是 CASSIA？ CASSIA (Collaborative Agent System for Single-cell Interpretable Annotation) 旨在利用多智能体大语言模型 (LLM) 的能力来增强细胞类型注释。我们将在本教程中介绍每个智能体",
    "url": "/zh/docs/python/introduction"
  },
  {
    "title": "质量评分",
    "slug": "quality-scoring-and-report-generation",
    "section": "docs",
    "lang": "python",
    "locale": "zh",
    "content": "质量评分有助于评估细胞类型注释的可靠性。CASSIA 通过 runCASSIAscorebatch 函数提供自动评分功能，该函数分析每个注释背后的推理和证据。 运行质量评分 参数详情 - inputfile: 完整注释结果 CSV 文件的路径（由 runCASSIAbatch 生成）。 - outputfile: 输出评分结果 CSV 文件名。 - maxworkers: 并行评分线程数。 - m",
    "url": "/zh/docs/python/quality-scoring-and-report-generation"
  },
  {
    "title": "RAG（可选）",
    "slug": "ragagent",
    "section": "docs",
    "lang": "python",
    "locale": "zh",
    "content": "这在您需要处理非常具体和详细的注释时特别有用。它可以显着提高注释的粒度和准确性。它自动提取标记信息并生成报告作为默认 CASSIA 流程的附加信息。 安装 用法 输出文件 所有输出（中间和最终）都保存在 \"TissueTypeSpecies\" 文件夹中的 txt 文件中。在我们的示例中，它是 LiverTiger 文件夹。 最终输出在 summaryclean.txt 文件中。该文件的内容稍后可用",
    "url": "/zh/docs/python/ragagent"
  },
  {
    "title": "安装 CASSIA",
    "slug": "setting-up-cassia",
    "section": "docs",
    "lang": "python",
    "locale": "zh",
    "content": "首先，使用 pip 安装 CASSIA 包： 导入 CASSIA 设置 API 密钥 要使用 OpenAI 的 GPT-4、Anthropic 的 Claude 或通过 OpenRouter 使用模型，您首先需要从提供商处获取 API 密钥，然后使用 setapikey 函数设置您的 API 密钥。 注意：您必须设置至少一个 API 密钥才能使用 CASSIA。 - 将 \"your-key\" 替换",
    "url": "/zh/docs/python/setting-up-cassia"
  },
  {
    "title": "亚群聚类分析（可选）",
    "slug": "subclustering-analysis",
    "section": "docs",
    "lang": "python",
    "locale": "zh",
    "content": "亚群聚类分析是一种更详细地研究特定细胞群体的强大技术。本教程将带您了解分析亚群（如 T 细胞或成纤维细胞）的过程。 工作流程摘要 1. 初始 CASSIA 分析 2. 亚群提取和处理（使用 Seurat 或 Scanpy） 3. 标记识别 4. CASSIA 亚群聚类分析 5. 不确定性评估（可选） 运行亚群聚类分析 我们建议首先应用默认的 CASSIA。然后，在目标聚类上，应用标准流程（Seur",
    "url": "/zh/docs/python/subclustering-analysis"
  },
  {
    "title": "故障排除",
    "slug": "troubleshooting",
    "section": "docs",
    "lang": "python",
    "locale": "zh",
    "content": "这里我们列出了用户可能遇到的一些常见错误。如果您有任何其他问题，请随时在最后一部分发表评论！ 认证错误 (Error 401) 常见原因 API 密钥未正确加载 API 密钥无效或过期 API 额度不足 解决方案 确保： 验证您的平台账户上有足够的额度 如有必要，通过平台的计费门户充值 文件未找到错误 常见原因 文件路径不正确 缺少输入文件 CASSIA 自动文件匹配问题 解决方案 指定路径时： ",
    "url": "/zh/docs/python/troubleshooting"
  },
  {
    "title": "不确定性量化（可选）",
    "slug": "uncertainty-quantification",
    "section": "docs",
    "lang": "python",
    "locale": "zh",
    "content": "CASSIA 中的不确定性量化有助于通过多次分析迭代和相似性评分来评估注释的可靠性。此过程对于以下方面至关重要： - 识别稳健的细胞类型分配 - 检测混合或模棱两可的聚类 - 量化注释置信度 - 了解预测的可变性 多重迭代分析 > ⚠️ 成本警告：使用 LLM 模型运行多次迭代可能会产生大量费用。每次迭代都会进行单独的 API 调用，因此总成本约为单次运行成本的 n 倍。建议从较小的迭代次数开始进",
    "url": "/zh/docs/python/uncertainty-quantification"
  },
  {
    "title": "注释增强扩展 (可选)",
    "slug": "annotation-boost-extra",
    "section": "docs",
    "lang": "r",
    "locale": "zh",
    "content": "该智能体是注释增强智能体的扩展版本。它使用自定义分析任务对特定簇执行额外分析。此功能通过允许使用大型语言模型对簇特定的生物学问题进行集中调查，扩展了基本注释功能。 用法 参数详情 - fullresultpath (字符串): 先前分析的完整结果 CSV 文件的路径。应包含带有 \"full.csv\" 后缀的输出名称。 - marker: 包含分析中使用的未处理标记数据的对象。 - outputna",
    "url": "/zh/docs/r/annotation-boost-extra"
  },
  {
    "title": "注释增强（可选）",
    "slug": "annotation-boost",
    "section": "docs",
    "lang": "r",
    "locale": "zh",
    "content": "注释增强是一种高级验证工具，通过多次迭代分析增强注释的置信度。它特别适用于： - 验证低置信度注释 - 获取特定细胞簇的详细见解 - 解决模糊的细胞类型分配 - 生成全面的验证报告 所需组件 1. 输入数据： - CASSIA批量分析的完整结果CSV - 原始标记基因文件（Seurat输出或自定义标记文件） - 簇上下文信息 - 特定簇标识符 2. 模型配置： - 推荐：通过OpenRouter使",
    "url": "/zh/docs/r/annotation-boost"
  },
  {
    "title": "批量处理",
    "slug": "batch-processing",
    "section": "docs",
    "lang": "r",
    "locale": "zh",
    "content": "CASSIA支持批量处理，可同时分析多个簇。本篇我们将介绍如何准备数据并高效运行批量分析。 模型推荐 如果您使用OpenRouter作为提供商，可以指定模型如\"openai/gpt-4o-2024-11-20\"或\"anthropic/claude-3.5-sonnet\"。以下是一些模型推荐： - Claude 3.5 Sonnet（最佳性能，略贵） - 模型ID：\"anthropic/claude",
    "url": "/zh/docs/r/batch-processing"
  },
  {
    "title": "Symphony Compare (高级)",
    "slug": "compare-cell-types",
    "section": "docs",
    "lang": "r",
    "locale": "zh",
    "content": "symphonyCompare 是一个高级模块，它协调多个 AI 模型以比较细胞类型并自动建立共识。它并行使用多个 AI 模型进行全面的细胞类型比较，当模型对最佳匹配细胞类型存在分歧时，自动触发讨论轮次。可以把它想象成一个专家生物学家小组在辩论并达成共识。 使用示例 函数参数 参数详情 - tissue (字符串): 被分析的组织类型（例如，\"blood\", \"brain\", \"liver\"）。 ",
    "url": "/zh/docs/r/compare-cell-types"
  },
  {
    "title": "快速模式",
    "slug": "fast-mode",
    "section": "docs",
    "lang": "r",
    "locale": "zh",
    "content": "CASSIA的快速模式提供了一个简化的、单行的解决方案，用于运行完整的分析流程。此模式在单个函数调用中结合了注释、评分和注释增强，使用优化的默认参数。 基本用法 将CASSIA结果添加回Seurat对象 完整参数选项 参数详情 - outputfilename: 输出文件夹和文件的基本名称。 - tissue: 样本的组织类型（例如，\"brain\"）。 - species: 样本的物种（例如，\"h",
    "url": "/zh/docs/r/fast-mode"
  },
  {
    "title": "可选智能体简介",
    "slug": "introduction-to-optional-agents",
    "section": "docs",
    "lang": "r",
    "locale": "zh",
    "content": "感谢您阅读到这里！基本的CASSIA工作流程对于大多数情况已经足够。然而，为了处理一些特殊情况，我们现在介绍几个高级智能体。 🤔 不确定性量化智能体（UQ智能体） 尽管大型语言模型（LLM）功能强大，但偶尔会产生不稳定的输出。不确定性量化（UQ）智能体通过采用基于共识的策略来缓解这一问题。例如，如果模型在单次尝试中的正确率为 80%，那么通过独立询问五次并通过多数投票汇总结果，理论上可以将准确率",
    "url": "/zh/docs/r/introduction-to-optional-agents"
  },
  {
    "title": "介绍",
    "slug": "introduction",
    "section": "docs",
    "lang": "r",
    "locale": "zh",
    "content": "欢迎来到CASSIA R教程！本指南将详细引导您更好地使用CASSIA包。 什么是CASSIA？ CASSIA (Collaborative Agent System for Single-cell Interpretable Annotation)旨在利用多智能体大型语言模型(LLMs)的能力来增强细胞类型注释。我们将在本教程中详细介绍每个智能体的原理以及使用方式。 图1：CASSIA的多智能体",
    "url": "/zh/docs/r/introduction"
  },
  {
    "title": "质量评分",
    "slug": "quality-scoring-and-report-generation",
    "section": "docs",
    "lang": "r",
    "locale": "zh",
    "content": "质量评分有助于评估细胞类型注释的可靠性。CASSIA通过runCASSIAscorebatch函数提供自动评分功能，该功能分析每个注释背后的推理和证据。 运行质量评分 基本用法 参数详情 - inputfile (字符串): 完整注释结果 CSV 文件的路径（由 runCASSIAbatch 生成）。 - outputfile (字符串): 输出评分结果 CSV 文件的名称。 - maxworke",
    "url": "/zh/docs/r/quality-scoring-and-report-generation"
  },
  {
    "title": "RAG（可选）",
    "slug": "ragagent",
    "section": "docs",
    "lang": "r",
    "locale": "zh",
    "content": "虽然RAG（检索增强生成）智能体在复杂或文献稀缺的环境中显著提高了注释准确性，但它目前仅在CASSIA包的Python版本中实现。 这是由于依赖性限制。我们认识到提供跨平台一致性的重要性，并正在积极努力尽快将RAG智能体引入R包。",
    "url": "/zh/docs/r/ragagent"
  },
  {
    "title": "设置CASSIA",
    "slug": "setting-up-cassia",
    "section": "docs",
    "lang": "r",
    "locale": "zh",
    "content": "首先，确保您已安装reticulate包和devtools包。 接下来，您需要安装CASSIA包。 设置Python环境 CASSIA依赖Python进行一些后端处理。当您加载CASSIA包时，它会尝试自动设置所需的Python环境。但是，如果您遇到问题，可以使用setupcassiaenv()函数自动创建和配置必要的Python环境。 此函数将： - 创建一个名为cassiaenv的新Pytho",
    "url": "/zh/docs/r/setting-up-cassia"
  },
  {
    "title": "单簇分析",
    "slug": "single-cluster-analysis",
    "section": "docs",
    "lang": "r",
    "locale": "zh",
    "content": "runCASSIA函数分析单个标记基因簇以识别细胞类型。 CASSIA可以一次性处理多个簇，因此此方法只适用于分析单个感兴趣的簇。 示例 有关模型设置和推荐的详细信息，请参阅 如何选择模型和提供商 部分。 示例代码 参数详情 - model: 用于分析的大语言模型。选项请参阅 设置 CASSIA。 - temperature: 控制模型输出的随机性（0 = 确定性，1 = 创造性）。默认为 0。 ",
    "url": "/zh/docs/r/single-cluster-analysis"
  },
  {
    "title": "子聚类分析（可选）",
    "slug": "subclustering-analysis",
    "section": "docs",
    "lang": "r",
    "locale": "zh",
    "content": "子聚类分析是一种强大的技术，用于更详细地研究特定细胞群体。本教程将指导您使用Cassia和Seurat分析子聚类群体（如T细胞或成纤维细胞）的过程。 先决条件 - 包含单细胞数据的Seurat对象 - 已安装并加载Cassia包 - 对R和单细胞分析有基本了解 工作流程摘要 1. 初始Cassia分析 2. 子簇提取和处理 3. 标记基因识别 4. Cassia子聚类分析 5. 不确定性评估（可选",
    "url": "/zh/docs/r/subclustering-analysis"
  },
  {
    "title": "故障排除",
    "slug": "troubleshooting",
    "section": "docs",
    "lang": "r",
    "locale": "zh",
    "content": "这里我们列出了用户可能遇到的一些常见错误。如果您有任何其他问题，请随时在最后一节留下评论！ 认证错误（错误401） 常见原因 API密钥未正确加载 无效或过期的API密钥 API信用额度不足 解决方案 确保： 验证您的平台账户上有足够的信用额度 如有必要，通过平台的计费门户添加资金 文件未找到错误 常见原因 文件路径不正确 缺少输入文件 CASSIA自动文件匹配问题 解决方案 指定路径时： 必要时",
    "url": "/zh/docs/r/troubleshooting"
  },
  {
    "title": "不确定性量化（可选）",
    "slug": "uncertainty-quantification",
    "section": "docs",
    "lang": "r",
    "locale": "zh",
    "content": "CASSIA中的不确定性量化通过多次分析迭代和相似性评分来评估注释可靠性。这个过程对以下方面至关重要： - 识别稳健的细胞类型分配 - 检测混合或模糊的簇 - 量化注释置信度 - 理解预测变异性 多次迭代分析 基本用法 > ⚠️ 成本警告：使用LLM模型运行多次迭代可能会产生显著成本。每次迭代都会进行单独的API调用，因此总成本将大约是单次运行成本的n倍。考虑从较小的迭代次数开始进行测试。 参数详",
    "url": "/zh/docs/r/uncertainty-quantification"
  },
  {
    "title": "基本注释",
    "slug": "basic-annotation",
    "section": "vignette",
    "lang": "python",
    "locale": "zh",
    "content": "本 Python 教程演示了使用 CASSIA 对单细胞 RNA 测序数据进行细胞类型注释的完整工作流程。我们将分析包含六个不同细胞群体的肠道细胞数据集： 1. 单核细胞 2. 浆细胞 3. cd8 阳性 alpha-beta T 细胞 4. 大肠过渡扩增细胞 5. 肠道肠内分泌细胞 6. 肠隐窝干细胞 设置和环境准备 首先，让我们安装并导入所需的包： 设置 API 密钥 加载数据 快速模式 以快",
    "url": "/zh/vignette/python/basic-annotation"
  },
  {
    "title": "使用 Scanpy 进行聚类和注释",
    "slug": "clustering-and-annotation",
    "section": "vignette",
    "lang": "python",
    "locale": "zh",
    "content": "本教程演示了如何使用 Scanpy 对预处理后的 AnnData 对象进行聚类，然后使用 CASSIA 对生成的聚类进行注释。我们假设质量控制步骤已经完成。 1. 安装和设置 1.1 所需的包 1.2 导入包 2. 探索您的预处理 AnnData 对象 在本教程中，我们将使用来自 GTEX 项目的乳腺组织数据集作为示例。该数据集为乳腺组织细胞类型提供了全面的参考。 我们假设数据集在 Broadce",
    "url": "/zh/vignette/python/clustering-and-annotation"
  },
  {
    "title": "扩展分析",
    "slug": "extended-analysis",
    "section": "vignette",
    "lang": "python",
    "locale": "zh",
    "content": "本教程涵盖 CASSIA 的高级功能，包括不确定性量化、注释增强和专用智能体。 可选步骤：不确定性量化 这对于研究注释的不确定性并可能提高准确性很有用。 注意：此步骤可能会很昂贵，因为将执行多次迭代。 可选步骤：对选定聚类进行注释增强 单核细胞聚类有时被注释为免疫细胞和神经元/胶质细胞的混合群体。 这里我们使用注释增强智能体来更详细地测试这些假设。 可选步骤：检索增强生成 (RAG) 这在您需要处",
    "url": "/zh/vignette/python/extended-analysis"
  },
  {
    "title": "教程简介",
    "slug": "introduction",
    "section": "vignette",
    "lang": "python",
    "locale": "zh",
    "content": "欢迎来到 CASSIA Python 教程部分。在这里，我们提供使用真实数据的分步教程，帮助您了解 CASSIA 的完整工作流程和功能。 可用教程 1. 基本注释 - 了解如何使用标记文件通过 CASSIA 注释细胞聚类。这涵盖了安装、设置、快速模式、批量分析和质量评分。 2. 聚类和注释 - 从原始数据开始的完整工作流程，使用 Scanpy。了解如何对单细胞数据进行聚类并在无缝管道中使用 CAS",
    "url": "/zh/vignette/python/introduction"
  },
  {
    "title": "CASSIA入门：基础分析",
    "slug": "basic-analysis",
    "section": "vignette",
    "lang": "r",
    "locale": "zh",
    "content": "本教程介绍使用CASSIA进行单细胞RNA测序分析的基本步骤。我们将重点介绍基础细胞类型注释的核心工作流程。 1. 安装和设置 在使用CASSIA之前，您需要安装软件包并设置必要的环境。 1.1 软件包安装 1.2 Python环境设置 CASSIA依赖Python进行部分后端操作。当您加载软件包时，环境会自动设置。如果遇到问题： 1.3 API密钥配置 CASSIA至少需要一个API密钥才能运行",
    "url": "/zh/vignette/r/basic-analysis"
  },
  {
    "title": "使用标记文件进行基础注释",
    "slug": "basic-annotation",
    "section": "vignette",
    "lang": "r",
    "locale": "zh",
    "content": "本教程介绍使用CASSIA进行细胞类型注释的基本步骤，适用于您已经准备好标记基因列表的情况。这非常适合您已经完成聚类分析并希望对细胞簇进行注释的场景。 1. 安装和设置 在使用CASSIA之前，您需要安装软件包并设置必要的环境。 1.1 软件包安装 1.2 Python环境设置 CASSIA依赖Python进行部分后端操作。当您加载软件包时，环境会自动设置。如果遇到问题，请运行以下命令手动设置Py",
    "url": "/zh/vignette/r/basic-annotation"
  },
  {
    "title": "使用Seurat进行聚类和注释",
    "slug": "clustering-and-annotation",
    "section": "vignette",
    "lang": "r",
    "locale": "zh",
    "content": "本教程演示如何对预处理的Seurat对象进行聚类，然后使用CASSIA对结果细胞簇进行注释。我们假设质量控制步骤已经完成。 1. 安装和设置 1.1 所需软件包 2. 探索预处理的Seurat对象 在本教程中，我们将使用GTEX项目的乳腺组织数据集作为示例。该数据集为乳腺组织细胞类型提供了全面的参考，可从以下链接下载： GTEX乳腺组织数据集 >[1] \"orig.ident\" \"nCountRN",
    "url": "/zh/vignette/r/clustering-and-annotation"
  },
  {
    "title": "使用可选代理进行扩展分析",
    "slug": "extended-analysis",
    "section": "vignette",
    "lang": "r",
    "locale": "zh",
    "content": "本教程演示如何使用CASSIA的可选代理进行更深入的分析和验证，从提供的标记基因文件开始。这些代理可以帮助您： - 评估注释的不确定性 - 提升特定细胞簇的注释质量 - 比较相似的细胞类型 - 执行亚聚类并分析亚群 1. 不确定性量化 运行多次注释迭代以提高准确性并评估结果的稳定性： 假设单次准确率为80%，通过重复注释5次，准确率将提高到约95%。 结果包含每个细胞簇的共识细胞类型注释和共识相似",
    "url": "/zh/vignette/r/extended-analysis"
  },
  {
    "title": "教程简介",
    "slug": "introduction",
    "section": "vignette",
    "lang": "r",
    "locale": "zh",
    "content": "欢迎来到CASSIA教程部分。在这里，我们提供基于真实数据的分步教程，帮助您全面了解CASSIA的完整工作流程和功能。 可用教程 我们的教程按复杂程度递增排列： 1. 使用标记文件进行基础注释 - 学习如何在已有标记基因的情况下使用CASSIA对细胞簇进行注释。 2. 使用可选代理的扩展分析 - 学习如何使用CASSIA的可选代理功能。 3. 从原始Seurat对象开始的聚类和注释 - 完整演示s",
    "url": "/zh/vignette/r/introduction"
  }
]
