// AUTO-GENERATED by sync_model_config.py — DO NOT EDIT MANUALLY
// Source: CASSIA_python/CASSIA/data/model_settings.json
// Generated from config version: 4.0.0

export const MODELS = {
  openai: { best: "gpt-6-astra", balanced: "gpt-5.6-terra", fast: "gpt-5.6-luna", recommended: "gpt-5.6-terra" },
  anthropic: { best: "claude-opus-5", balanced: "claude-sonnet-5", fast: "claude-haiku-4-5", recommended: "claude-sonnet-5" },
  openrouter: { best: "openai/gpt-6-astra", balanced: "anthropic/claude-sonnet-5", fast: "google/gemini-3.8-flash", recommended: "anthropic/claude-sonnet-5" },
} as const;

export const DEFAULT_MODELS: Record<string, string> = {
  openai: "gpt-5.6-terra",
  anthropic: "claude-sonnet-5",
  openrouter: "anthropic/claude-sonnet-5",
};

export const PIPELINE_DEFAULTS = {
  openai: { annotation: "gpt-5.6-terra", score: "gpt-5.6-terra", merge: "gpt-5.6-luna", annotationBoost: "gpt-5.6-terra" },
  anthropic: { annotation: "claude-sonnet-5", score: "claude-sonnet-5", merge: "claude-haiku-4-5", annotationBoost: "claude-sonnet-5" },
  openrouter: { annotation: "openai/gpt-5.6-terra", score: "anthropic/claude-sonnet-5", merge: "google/gemini-3.8-flash", annotationBoost: "anthropic/claude-sonnet-5" },
} as const;

export const AGENT_DEFAULTS = {
  openrouter: {
    annotation: { model: "openai/gpt-5.6-terra", temperature: 0 },
    scoring: { model: "anthropic/claude-sonnet-5", temperature: 0 },
    merging: { model: "google/gemini-3.8-flash", temperature: 0 },
    subclustering: { model: "anthropic/claude-sonnet-5", temperature: 0 },
    subclustering_n: { model: "anthropic/claude-sonnet-5", temperature: 0.3 },
    annotation_boost: { model: "anthropic/claude-sonnet-5", temperature: 0.1 },
    uncertainty: { model: "openai/gpt-5.6-terra", temperature: 0 },
  },
  openai: {
    annotation: { model: "gpt-5.6-terra", temperature: 0 },
    scoring: { model: "gpt-5.6-terra", temperature: 0 },
    merging: { model: "gpt-5.6-luna", temperature: 0 },
    subclustering: { model: "gpt-5.6-terra", temperature: 0 },
    subclustering_n: { model: "gpt-5.6-terra", temperature: 0.3 },
    annotation_boost: { model: "gpt-5.6-terra", temperature: 0.1 },
    uncertainty: { model: "gpt-5.6-terra", temperature: 0 },
  },
  anthropic: {
    annotation: { model: "claude-sonnet-5", temperature: 0 },
    scoring: { model: "claude-sonnet-5", temperature: 0 },
    merging: { model: "claude-haiku-4-5", temperature: 0 },
    subclustering: { model: "claude-sonnet-5", temperature: 0 },
    subclustering_n: { model: "claude-sonnet-5", temperature: 0.3 },
    annotation_boost: { model: "claude-sonnet-5", temperature: 0.1 },
    uncertainty: { model: "claude-sonnet-5", temperature: 0 },
  },
} as const;

export const SYMPHONY_PRESETS = {
  premium: ["google/gemini-3.1-pro-preview", "anthropic/claude-opus-5", "openai/gpt-6-astra", "x-ai/grok-4.6"],
  budget: ["deepseek/deepseek-v4-flash-0731", "openai/gpt-5.6-luna", "meta-llama/llama-4-maverick", "google/gemini-3.5-flash-lite"],
} as const;

export const MODEL_PERSONAS: Record<string, string> = {
  "google/gemini-3.1-pro-preview": "Dr. Emmy Noether",
  "anthropic/claude-opus-5": "Dr. Claude Shannon",
  "openai/gpt-6-astra": "Dr. Albert Einstein",
  "x-ai/grok-4.6": "Dr. Marie Curie",
  "deepseek/deepseek-v4-flash-0731": "Dr. Alan Turing",
  "openai/gpt-5.6-luna": "Dr. Nikola Tesla",
  "meta-llama/llama-4-maverick": "Dr. Ada Lovelace",
  "google/gemini-3.5-flash-lite": "Dr. Rosalind Franklin",
};
