// AUTO-GENERATED by sync_model_config.py — DO NOT EDIT MANUALLY
// Source: CASSIA_python/CASSIA/data/model_settings.json
// Generated from config version: 3.0.0

export const MODELS = {
  openai: { best: "gpt-5.4", balanced: "gpt-4o", fast: "gpt-5.4-mini", recommended: "gpt-5.4" },
  anthropic: { best: "claude-opus-4-6", balanced: "claude-sonnet-4-6", fast: "claude-haiku-4-5", recommended: "claude-sonnet-4-6" },
  openrouter: { best: "anthropic/claude-sonnet-4.6", balanced: "openai/gpt-5.4", fast: "google/gemini-3-flash-preview", recommended: "anthropic/claude-sonnet-4.6" },
} as const;

export const DEFAULT_MODELS: Record<string, string> = {
  openai: "gpt-5.4",
  anthropic: "claude-sonnet-4-6",
  openrouter: "anthropic/claude-sonnet-4.6",
};

export const PIPELINE_DEFAULTS = {
  openai: { annotation: "gpt-5.4", score: "gpt-5.4", merge: "gpt-5.4-mini", annotationBoost: "gpt-5.4" },
  anthropic: { annotation: "claude-sonnet-4-6", score: "claude-sonnet-4-6", merge: "claude-haiku-4-5", annotationBoost: "claude-sonnet-4-6" },
  openrouter: { annotation: "openai/gpt-5.4", score: "anthropic/claude-sonnet-4.6", merge: "google/gemini-3-flash-preview", annotationBoost: "anthropic/claude-sonnet-4.6" },
} as const;

export const AGENT_DEFAULTS = {
  openrouter: {
    annotation: { model: "openai/gpt-5.4", temperature: 0 },
    scoring: { model: "anthropic/claude-sonnet-4.6", temperature: 0 },
    merging: { model: "google/gemini-3-flash-preview", temperature: 0 },
    subclustering: { model: "anthropic/claude-sonnet-4.6", temperature: 0 },
    subclustering_n: { model: "anthropic/claude-sonnet-4.6", temperature: 0.3 },
    annotation_boost: { model: "anthropic/claude-sonnet-4.6", temperature: 0.1 },
    uncertainty: { model: "openai/gpt-5.4", temperature: 0 },
  },
  openai: {
    annotation: { model: "gpt-5.4", temperature: 0 },
    scoring: { model: "gpt-5.4", temperature: 0 },
    merging: { model: "gpt-5.4-mini", temperature: 0 },
    subclustering: { model: "gpt-5.4", temperature: 0 },
    subclustering_n: { model: "gpt-5.4", temperature: 0.3 },
    annotation_boost: { model: "gpt-5.4", temperature: 0.1 },
    uncertainty: { model: "gpt-5.4", temperature: 0 },
  },
  anthropic: {
    annotation: { model: "claude-sonnet-4-6", temperature: 0 },
    scoring: { model: "claude-sonnet-4-6", temperature: 0 },
    merging: { model: "claude-haiku-4-5", temperature: 0 },
    subclustering: { model: "claude-sonnet-4-6", temperature: 0 },
    subclustering_n: { model: "claude-sonnet-4-6", temperature: 0.3 },
    annotation_boost: { model: "claude-sonnet-4-6", temperature: 0.1 },
    uncertainty: { model: "claude-sonnet-4-6", temperature: 0 },
  },
} as const;

export const SYMPHONY_PRESETS = {
  premium: ["google/gemini-3-pro-preview", "anthropic/claude-sonnet-4.6", "openai/gpt-5.4", "x-ai/grok-4"],
  budget: ["deepseek/deepseek-v3.2", "x-ai/grok-4.20-beta", "moonshotai/kimi-k2.5", "google/gemini-3-flash-preview"],
} as const;

export const MODEL_PERSONAS: Record<string, string> = {
  "google/gemini-3-pro-preview": "Dr. Emmy Noether",
  "anthropic/claude-sonnet-4.6": "Dr. Claude Shannon",
  "openai/gpt-5.4": "Dr. Albert Einstein",
  "x-ai/grok-4": "Dr. Marie Curie",
  "deepseek/deepseek-v3.2": "Dr. Alan Turing",
  "x-ai/grok-4.20-beta": "Dr. Nikola Tesla",
  "moonshotai/kimi-k2.5": "Dr. Ada Lovelace",
  "google/gemini-3-flash-preview": "Dr. Rosalind Franklin",
};
