---
title: "R Notebook"
output: html_notebook
---

```{r}
library(SingleR)
library(celldex)
library(Seurat)
library(dplyr)
```



```{r}
process_singleR <- function(data_object) {
  # Function to get the majority label
  get_majority_label <- function(labels) {
    uniqv <- unique(labels)
    uniqv[which.max(tabulate(match(labels, uniqv)))]
  }
  
  # Get the current cell type clusters and SingleR annotations
  current_clusters <- data_object$celltype
  singleR_annotations <- data_object$singleR
  
  # Create a data frame with current clusters and SingleR annotations
  annotation_df <- data.frame(
    cluster = current_clusters,
    singleR_label = singleR_annotations
  )
  
  # Group by cluster and get the majority SingleR label for each cluster
  modified_singleR <- annotation_df %>%
    group_by(cluster) %>%
    summarise(modified_singleR = get_majority_label(singleR_label))
  
  # Add the data object name to the result
  modified_singleR$data_object_name <- deparse(substitute(data_object))
  
  # Write the result to a CSV file
  output_filename <- paste0("modified_singleR_", deparse(substitute(data_object)), ".csv")
  write.csv(modified_singleR, file = output_filename, row.names = FALSE)
  
  return(modified_singleR)
}
```





```{r}
hpca.se <- HumanPrimaryCellAtlasData()

skeletalmuscle=subset(gtex,tissue=="skeletalmuscle")

skeletalmuscle_sce=as.SingleCellExperiment(skeletalmuscle)

pred.skeletalmuscle_sce <- SingleR(test = skeletalmuscle_sce, ref = hpca.se, assay.type.test=1,
    labels = hpca.se$label.main)

skeletalmuscle$singleR=pred.skeletalmuscle_sce$labels

result <- process_singleR(skeletalmuscle)

```
